In [37]:
import pandas as pd
animals_data = {'Name': ['Lion', 'Tiger', 'Elephant', 'Giraffe'],
                'Species': ['Carnivore', 'Carnivore', 'Herbivore', 'Herbivore'],
                'Weight': [190, 160, 600, 1000],
                'Count': [5, 4, 8, 15]}

columns=['Name', 'Species','Weight','Count']
df = pd.DataFrame(animals_data)
df

       Name    Species  Weight  Count
0      Lion  Carnivore     190      5
1     Tiger  Carnivore     160      4
2  Elephant  Herbivore     600      8
3   Giraffe  Herbivore    1000     15

In [33]:
#2
df.to_csv('animals.csv', index=False)

In [32]:
#3
df = pd.read_csv('animals.csv')

In [38]:

df.describe()

            Weight      Count
count     4.000000   4.000000
mean    487.500000   8.000000
std     396.263801   4.966555
min     160.000000   4.000000
25%     182.500000   4.750000
50%     395.000000   6.500000
75%     700.000000   9.750000
max    1000.000000  15.000000

In [34]:
#первые строки
N=1
df.head(N)

   Name    Species  Weight  Count
0  Lion  Carnivore     190      5

In [19]:
#последние строки
N = 3
df.tail(N)

       Name    Species  Weight  Count
1     Tiger  Carnivore     160      4
2  Elephant  Herbivore     600      8
3   Giraffe  Herbivore    1000     15

In [ ]:
#столбец
df['Weight']

0     190
1     160
2     600
3    1000
Name: Weight, dtype: int64

In [ ]:
#строка
df[2:4]

       Name    Species  Weight  Count
2  Elephant  Herbivore     600      8
3   Giraffe  Herbivore    1000     15

In [20]:
#cortirovka
df.groupby('Name').agg({'Weight': 'mean'})

          Weight
Name
Elephant   600.0
Giraffe   1000.0
Lion       190.0
Tiger      160.0

In [36]:
#пропущенные значения(заполнение)
import pandas as pd
animals1_data = {'Name': ['Lion', None, 'Elephant', 'Giraffe'],
                'Species': ['Carnivore', None, 'Herbivore', 'Herbivore'],
                'Weight': [190, None, 600, 1000],
                'Count': [5, None, 8, 15]}

df1 = pd.DataFrame(animals1_data)
df1.fillna("ERROR 404", inplace=True)
df1

        Name    Species     Weight      Count
0       Lion  Carnivore      190.0        5.0
1  ERROR 404  ERROR 404  ERROR 404  ERROR 404
2   Elephant  Herbivore      600.0        8.0
3    Giraffe  Herbivore     1000.0       15.0

In [40]:
#пропущенные значения(удаление)
import pandas as pd
animals1_data = {'Name': ['Lion', None, 'Elephant', 'Giraffe'],
                'Species': ['Carnivore', None, 'Herbivore', 'Herbivore'],
                'Weight': [190, None, 600, 1000],
                'Count': [5, None, 8, 15]}

df1 = pd.DataFrame(animals1_data)
df1.dropna(inplace=True)
df1

       Name    Species  Weight  Count
0      Lion  Carnivore   190.0    5.0
2  Elephant  Herbivore   600.0    8.0
3   Giraffe  Herbivore  1000.0   15.0

In [47]:
#сортировка данных
df_sorted = df.sort_values(by='Weight', ascending=True)
df_sorted = df.sort_values(by='Count', ascending=True)
df_sorted

       Name    Species  Weight  Count
1     Tiger  Carnivore     160      4
0      Lion  Carnivore     190      5
2  Elephant  Herbivore     600      8
3   Giraffe  Herbivore    1000     15

In [57]:
#фильтрация
result=df[df['Weight'] > 500]
result

       Name    Species  Weight  Count
2  Elephant  Herbivore     600      8
3   Giraffe  Herbivore    1000     15

In [60]:
#переименнование
df = df.rename(columns={'Weight': 'Вес'})
df = df.rename(columns={'Name': 'Название'})
df = df.rename(columns={'Species': 'Вид'})
df = df.rename(columns={'Count': 'Значение'})
df

   Название        Вид   ВЕС  Значение
0      Lion  Carnivore   190         5
1     Tiger  Carnivore   160         4
2  Elephant  Herbivore   600         8
3   Giraffe  Herbivore  1000        15